### ISSUE TITLE
No "File" menu - no "New Window" option

### ISSUE THREAD

**Issue by llabusch93** [puneetsl/lotion#101]
When I first run Lotion _(installed as "Web" version)_ there was a file menu, where I could click "Open new Window".
The "File" menu is vanished and also the Shortcut `Ctrl + Shift + N` does not bring up a new window.

Even if I click right on the Lotion icon and select `Open new Window` nothing happens...
I already uninstalled Lotion and reinstalled it with no effect...

OS: POP! OS 20.10

Any advises?

Thanks a lot!

**Comment by joshpetit** [comment]
Hey! So if you want to use multiple windows you will have to use the native version. The web version doesn't support multiple windows. You can switch your installation with `./setup.sh native` and it should work!

**Comment by puneetsl** [comment]
you can have both native and non-native versions installed, I'll see if we can make that configurable.
something like `./setup.sh all`

**Comment by puneetsl** [comment]
Just as a hacky way of solving, you can `CTRL+click` on any notion link and it would open a new window
