### ISSUE TITLE
Is the lotion snap official?

### ISSUE THREAD

**Issue by smomims** [puneetsl/lotion#103]
I installed the lotion snap and after opening the application, it only goes to the homepage of notion.so and after a while gives me JavaScript errors. Did I just do something wrong?

**Comment by joshpetit** [comment]
No, that isn't something Puneet created as far as I know. I don't recognize the vendor either.

**Comment by puneetsl** [comment]
Notion snap was created by one of the users of Notion, however there is a possibility of official snap soon
