### ISSUE TITLE
It doesn't load

### ISSUE THREAD

**Issue by LucasDondo** [puneetsl/lotion#105]
# Problem
I installed Lotion with sudo for global installation, the native version. Once installed, every time I open it, it shows just a blank screen (with the window bars above).
I rebooted but it still doesn't work. I have no idea why it is malfunctioning.
# System
**OS**: ZorinOS Core 15.3 (Ubuntu 18.04)
# Screenshot
![Screenshot](https://user-images.githubusercontent.com/59975541/114757841-b8d7ad00-9d32-11eb-9cd7-eb2a3ef71986.png)

**Comment by WhsCloud** [comment]
Same issue as #68 Would like to mention I Am getting same issue with the newest update on Parrot OS, thinking its an KDE/Debian issue?

**Comment by LucasDondo** [comment]
Oh! I looked for for any similar issue but I didn't see that one! Sorry!
Yes, could be Debian, or maybe Ubuntu. (Or something else completely different)
I will now close this issue and comment in the other one.
