### ISSUE TITLE
Any way to run multiple instances?

### ISSUE THREAD

**Issue by juliangums** [puneetsl/lotion#11]
So I can log in with different email addresses parallely

**Comment by puneetsl** [comment]
Not at this time! The only way right now is to open Notion in Chrome for other account.
I'll try to find some other ways to do this when I get time.

**Comment by closetogermany** [comment]
Thanks for replying!

**Comment by puneetsl** [comment]
I have updated the app, Now you can clone at two different places and it should work for multiple instances. You can change icon.png just to have different look. It won't be that pleasant but it will work.

**Comment by puneetsl** [comment]
Closing as it is fixed!
