### ISSUE TITLE
Can't quit program with keyboard shortcut

### ISSUE THREAD

**Issue by huyndnse63331** [puneetsl/lotion#13]
Hi, i really enjoyed this project. But it will be better if you add **Ctrl + Q** as quit function. Since v0.02, i can't use **Alt + F4** to exit the program anymore, it just minimizes. Please consider my option. Thanks so muchhhh!

**Comment by puneetsl** [comment]
This is by design. (There is no big change in v0.2, if v0.1 has worked for you can still use it)
If you want to quit in v0.2 you can go to the tray icon and quit from there. 
I'll consider adding a shortcut to quit the app for real.
