### ISSUE TITLE
Check spelling / typos

### ISSUE THREAD

**Issue by guillaumefrd** [puneetsl/lotion#14]
Hi, 
Thanks for this awesome app that I'm using every day! 
I've been wondering if it would be possible to underline spelling errors, like it is done in any browser. I think it would be a useful feature to avoid typos!

**Comment by puneetsl** [comment]
Great Idea! but right now it is difficult to implement. I'll try to add in next versions.

**Comment by puneetsl** [comment]
Hopefully, this features will be rolled out in the next version as I see builtin spell checker got added to electron recently:
https://github.com/electron/electron/pull/20692

**Comment by haydn-jones** [comment]
What is the status of spellcheck support?

**Comment by brendandebeasi** [comment]
This is a feature I would fine super useful as well. I am currently using Lotion to write some papers for college and I have to copy+pasted into word prior to submitting them.

Thanks for your time and effort!

**Comment by Spritan** [comment]
I believe there is a way to add Grammarly chrome extension to electron
via https://github.com/getstation/electron-chrome-extension

**Comment by thanhtacles** [comment]
I'm having the opposite issue where it's impossible to disable spellcheck. Normally the context menu has this option, but it's just totally blank now, so you get a bunch of red squiggles everywhere there are terms. And you can't add to dictionary either because that's also missing from context menu.

**Comment by puneetsl** [comment]
Spell checking is by default in version 0.05, and you can easily add it to the dictionary, however, no way to disable the dict right now
