### ISSUE TITLE
Can't login using google account

### ISSUE THREAD

**Issue by felipe-michelon** [puneetsl/lotion#17]
When i try to sign in using my google account, i get this message:

![image](https://user-images.githubusercontent.com/29461168/71740969-68d61f00-2e3c-11ea-97ab-61c668a2ab5c.png)

Any ideas?

**Comment by puneetsl** [comment]
I am not able to replicate it. Can you post more details? such as Distro, kernel version, if you have Google Chrome, Chromium or Firefox installed, are you logging in through edu third party google apps account?

Usually, these kinds of problems occur when you try to login with gapps email (non @gmail accounts) for solving this
![image](https://user-images.githubusercontent.com/6509604/71927135-d1860a00-3162-11ea-8d6a-3d639b8d9cec.png)

and login with the secret code sent out to your email. Let me know if that helps.

**Comment by will-sauer** [comment]
I tried using the "continue with email" option and got similar. I am able to log in but at the top of all of the pages, I get the following error (see attached). The information box says the following: 
>>> You can no longer make edits. Cannot open IndexDB. Your chrome profile may be damaged. 
If you changed any chrome:://flags then please reset them, then restart your browser. If issues persist, try making a new chrome user. Contact support if that doesn't fix the issue.

![notion](https://user-images.githubusercontent.com/25811267/71997308-a5729380-320b-11ea-8ec7-bbab583a164b.png)

**Comment by puneetsl** [comment]
Can you please try to reinstall from scratch? Might be cache got corrupted. 
Also, It will be very helpful if you can give info about Distro and Linux kernel version. I am unable to replicate this behavior on my system.

**Comment by will-sauer** [comment]
No problem - will do that and let you know.
kernel: `5.3.0-20-generic`
distro: `Pop!_OS 18.04 LTS`

**Comment by closetogermany** [comment]
I believe Google will allow you to login after some recent changes @will-sauer -- can you take a shot at logging in with your acct?

**Comment by closetogermany** [comment]
@puneetsl I was able to replicate the instance @will-sauer is describing by 

- Closing `lotion` ( child processes remain, no `pkill` ) 
- Re-launch `lotion` 
- New instance is started, upon logging in - it breaks the session. 
- At this point, you have to kill all `chrome` and `lotion`/`notion` processes 
- Relaunch `lotion` 
- Relaunch `chrome`

**Comment by puneetsl** [comment]
Thanks @closetogermany, for steps to achieve this issue. 
I added this as design due issue #11. But I think it added to the confusion than to actually solve a problem. So I guess I'll update lotion to only work for a single instance.

Onto Version 0.3 :)!

**Comment by maciejmotyka** [comment]
I experience the same issue, when I try to **Sign up** with Google.

I registered with `continue with email` instead, but the problem resurfaced when I tried to connect my `Trello` and `Google drive` accounts. I managed to connect `Trello` using non-google login, but couldn't connect `Google drive` since it only provides the Google login. In the end I used the website to connect it.

kernel: `5.3.0-29-generic`
distro: `Ubuntu 19.10 MATE`

**Comment by Jeoffreybauvin** [comment]
Same issue here

Debian 10.3 (4.19.0-6-amd64)

**Comment by puneetsl** [comment]
Can you check now with an updated version?

**Comment by felipe-michelon** [comment]
@puneetsl Now it works! I logged with a gapps email and it went fine

**Comment by puneetsl** [comment]
Alright closing this issue as it is fixed

**Comment by maciejmotyka** [comment]
I have just updated to `Lotion 0.03` and the "Continue with Google" login still complains that
>This browser or app might not be secure.

**Comment by Jeoffreybauvin** [comment]
Same than @maciejmotyka :(.

**Comment by iarmankhan** [comment]
Same here! Why this issue is closed?

**Comment by closetogermany** [comment]
@maciejmotyka  @Jeoffreybauvin @iarmankhan Have you taken any troubleshooting steps? What platform are you on. Could you be more descriptive with your complaints? "It doesn't work" isn't exactly the most robust submission.

**Comment by maciejmotyka** [comment]
@closetogermany thanks for calling me lazy - it helped me to resolve this.
Here's what I did:
```console
# Find and remove all lotion and notion files and directories (I used fdfind)
$ fd --hidden lotion /
$ fd --hidden notion /

# Make sure no lotion or chrome processes are running; pkill if found
$ ps aux | grep chrome ; ps aux | grep lotion

# Clone the repo
$ git clone https://github.com/puneetsl/lotion.git

# Install lotion
$ cd lotion ; ./install.sh

# Run lotion
$ nohup ./Lotion/Lotion &
```
Log in with Google worked. I'm using Ubuntu MATE 20.04
