### ISSUE TITLE
Use the native browser to open links

### ISSUE THREAD

**Issue by bitwhys** [puneetsl/lotion#18]
### Expected behavior
Just as with other native applications that support active links, clicking the link should open its destination either in a new native browser instance or in a new tab within an active browser window.

### Actual behavior
Links are opened in a browser instance associated with the application. This means none of my extensions are present, cookies, bookmarks. Which is bad since the links stored in a Notion file where created in that environment.

**Comment by puneetsl** [comment]
You are right, it is indeed bothering me as well. I'll fix this in the next version.

**Comment by bitwhys** [comment]
Sweet thanks. 

I really love what you've provided, if I can help in any way let me know.

**Comment by puneetsl** [comment]
Updated to version 0.03, it should fix this issue!
Can you please update and test if it works for you? You can always rollback to previous version if things don't work for you.

**Comment by bitwhys** [comment]
Just checked it out...works perfectly. Thanks a lot bro
