### ISSUE TITLE
Franz Integration

### ISSUE THREAD

**Issue by Msouza91** [puneetsl/lotion#20]
Since it's already an electron based app, would it be simple to integrate it with [Franz](https://www.meetfranz.com)? I mean, if you have a premium account one can log in to notion and have basically the same functionality, but if you were to provide a way to integrate it in the ecosystem, people without much experience could use it there...

**Comment by TheMartes** [comment]
Although it is an electron app, franz will require more cooperation with notion itself rather than third party app.

**Comment by puneetsl** [comment]
Thanks @TheMartes  .. Couldn't have said it better

Closing this issue for now
