### ISSUE TITLE
Clicking close (X) button in the title bar and then relaunching causes to launch a separate instance

### ISSUE THREAD

**Issue by ajdajd** [puneetsl/lotion#21]
Replication steps:

1. Click the close (X) button. The app remains open (the app icon is present in the top panel/system tray or check via System Monitor).
2. Relaunch the app. This opens a separate instance (secondary app icon in the top panel).

Is this intended behavior?

Side note: separate instance launches in light mode (my config is dark mode).

**Comment by puneetsl** [comment]
I will fix this bug soon keep an eye on the new version. Right now just busy with other stuff.

**Comment by puneetsl** [comment]
Updated to version 0.03, it should fix this issue!
Can you please update and test if it works for you? You can always rollback to previous version if things don't work for you.

**Comment by puneetsl** [comment]
Others who reported a similar problem reported that it got fixed in the new version.

Closing this issue now! If you think it is not fixed please reopen this.
