### ISSUE TITLE
Cannot save changes

### ISSUE THREAD

**Issue by kyw8738** [puneetsl/lotion#22]
I got a problem. When I quit and then start lotion, lotion doesn't load my content table. Although lotion loads workspaces and titles, but I can see only a title on the page. And I can see a mention 

> "Cannot save changes" 

colored red on the white page.
Tooltip described that 

> "You can no longer make edits: Cannot open Indexed DB. Your Chrome profile may be damaged. If you changed any chrome://flags then please reset, then restart your browser.~~" 

I did it. But it not worked. 
I would like to attach a log for your convenience.  But i don't know where log file is. 

My Linux PC 
 - Ubuntu 18.04.3 LTS
 - Connected Internet on Proxy network environment. 

- Fortunately, I see a table with Android Application. -

I noticed that the same issue exists in other thread.
https://github.com/puneetsl/lotion/issues/1#issuecomment-566556510
> Hi, I'm getting issues with both lotion and native lotion. When I finally got the install.sh to execute, (which was not trivial with lots of permission errors and file does not exist errors) I am able to open a desktop version of lotion (without a desktop icon), but I need to log in every time. I get an error in the app that says:
> 
> "Cannot save my changes. You can no longer make edits: Cannot open IndexedDB. Your chrome profile may be damaged."
> 
> I tried getting native notion using the above method and was able to move the app.asar to the correct folder, but I still don't have a desktop application for native notion. I should note that I needed to manually move the lotion.desktop to my /usr/share/applications in order for notion to open outside of the terminal. Any tips here? Notion is my favorite productivity app and I recently started using linux.

**Comment by kyw8738** [comment]
I found a clue. Even though i quit lotion by clicking quit button on the lotion app,  It still alive until I quit manually from the taskbar. After I quitted or killed the process remainning, Lotion worked fine. I guess that this issue is sort of multi access permission problem.

![Screenshot from 2020-02-18 10-11-57](https://user-images.githubusercontent.com/6323052/74695773-8dddf000-5238-11ea-91e2-cf958e80a8e7.png)

"ps" command also show me that lotion processes still alive after i quit app.

**Comment by puneetsl** [comment]
I will fix this issue in a week or so, keep an eye on version 0.4 release

**Comment by puneetsl** [comment]
Updated to version 0.03, it should fix this issue!
Can you please update and test if it works for you? You can always rollback to previous version if things don't work for you.

**Comment by puneetsl** [comment]
Others who reported the same problem reported it got fixed in the new version.

Closing this issue now! If you think it is not fixed please reopen this.

**Comment by ThyMakra** [comment]
Hi @puneetsl. I am facing this same problem right now when I open notion on Chrome. But I notice that when I open the same Notion page through Chromium, it works fine.
