### ISSUE TITLE
Button / Shortcut to go back 

### ISSUE THREAD

**Issue by guillaumefrd** [puneetsl/lotion#23]
Hi, 
This app is amazing, so thanks! The only important feature missing in my opinion would be a button and a shortcut to go back to the previous visited page. There is a button in the Windows and Mac OS app on the top. If the shortcut could be ALT + left arrow it would be the really could!

**Comment by puneetsl** [comment]
update your version to 0.03 and you can use `CTRL`+`[` and `CTRL`+`]` to go _backward_ and _forward_ respectively

closing for now! It will be difficult to add forward and backward specific buttons in this version.
I'll try to add it in future versions if required.

**Comment by guillaumefrd** [comment]
Thanks for the answer!
I updated but strange behavior happens with my azerty keyboard, where the brackets are only accessible when pressing `AltGr`. with I manage to go backward with `CTRL + AltGr + ]` "(which should actually corresponds to forward). And `CTRL + AltGr + [`

**Comment by guillaumefrd** [comment]
Thanks for the answer!
I updated to 0.03 but strange things happens with my azerty keyboard, where the brackets are only accessible when pressing `AltGr`. 
I managed to go backward with `CTRL + AltGr + ]` "(which should actually corresponds to forward). And `CTRL + AltGr + [` doesn't do anything. 
In the top menu (accessible with `Alt`), the back and forward are working as expected.
