### ISSUE TITLE
Installation On i3 Manjaro

### ISSUE THREAD

**Issue by Ninja73737** [puneetsl/lotion#24]
Hello! I'm running a relatively fresh install of i3 Manjaro but after I run the install script the output all appears successful, but there doesn't seem to be any way to run the program. It doesn't appear in dmenu or on my desktop or anywhere else I could run it from. This could definitely be user error though. Is there a specific file inside the installation that I could run to open the program?

**Comment by snbk97** [comment]
@Ninja73737 You could try enabling the usernamespace restriction on your kernel by running

`sysctl -w kernel.unprivileged_userns_clone=1`

And then running your app. It might work this way.

**Comment by Ninja73737** [comment]
The main issue was that I didn't know how to run my app 😅
I figured it out though!
