### ISSUE TITLE
Empty window

### ISSUE THREAD

**Issue by Letyachee** [puneetsl/lotion#25]
Hi,

Thank you for you job! But it seems that I have a problem: after opening the app just an empty windows appears. I've just recently came to linux and probably do not understand how to open it properly. What may be the reason?
![Untitled](https://user-images.githubusercontent.com/49593409/76161034-c5e99c00-612f-11ea-9af0-82c85b18834d.jpg)

**Comment by puneetsl** [comment]
Updated to version 0.03, it should fix this issue!
Can you please update and test if it works for you? you can always rollback to previous version if things don't work for you.

**Comment by Letyachee** [comment]
Thank you very much! It works now.

**Comment by puneetsl** [comment]
Awesome!

Closing this issue

**Comment by slarrain** [comment]
Hi @puneetsl 
I'm running into the same issue.
Fedora 31, Lotion version 0.03.
Any ideas as to what might be causing this issue. It was working fine just the other day. This happened a couple of weeks ago, and I just reclone the repo and reinstall it and it came back.
Thanks!
