### ISSUE TITLE
Lotion Offline Sync

### ISSUE THREAD

**Issue by iAmG-r00t** [puneetsl/lotion#30]
Hi I have tried to follow the wiki on this but it seems like it doesn't work in the lotion folder I can only see Lotion/resources/app so should I create a new folder named Notion/resources in the lotion folder or rename the folder app in lotion/Lotion/resources to something else then place the app.asar inside lotion/Lotion/resources.

Because I can't see Notion folder inside lotion folder.

Kindly assist, I would really love to have the offline mode for moments when my PC is offline.

**Comment by iAmG-r00t** [comment]
@puneetsl kindly assist does this option still work??

**Comment by puneetsl** [comment]
Sorry for the late reply! 
You can use the old release for now to get offline mode:
https://github.com/puneetsl/lotion/releases/tag/V-0.02

Newer mode will require additional steps to do the same and end result will be same.
