### ISSUE TITLE
Alt + Left / Right arrow doesn't work throughout the system.

### ISSUE THREAD

**Issue by Icy-Breath** [puneetsl/lotion#33]
Hi, thank you for the great project.

I've been using lotion since Jul 2019 (0.01 version by the README), and I updated to the new version (0.03) last week for the first time since then.

After the update, **Alt + Left / Right** keybindings don't work throughout the system.

For example, in chrome, navigate back & forward doesn't work. 
(Not only chrome, the same thing happens on all the apps only except on notion app.)

If I do `pkill -9 Lotion`, then everything comes back to normal.

I didn't have this problem with July 2019 version.

My current environment:
**OS** : Linux Mint 19.1
**Desktop** : Cinnamon
**Expected** : Alt + Left / Right shortcuts work properly by the apps.
**Actual** : Alt + Left / Right only work on Notion, all other apps don't respond to those keybindings.

**Comment by puneetsl** [comment]
I could replicate this bug, I would try to fix this in next release

**Comment by puneetsl** [comment]
let me know if this fix worked for you

**Comment by Icy-Breath** [comment]
Issue fixed! Thanks.
