### ISSUE TITLE
System tray icon is missing

### ISSUE THREAD

**Issue by gammons** [puneetsl/lotion#34]
Hi there! Thanks for all your work on this project.   Notion is great and I'm so glad I can use it on Linux.

I noticed with the 0.02 release, the system tray icon seems missing.

**Comment by puneetsl** [comment]
Yes, 0.02 had this issue. Can you check out the 0.03 version?

Is there a specific reason you are using 0.02?

**Comment by gammons** [comment]
haha.  Thanks @puneetsl !

However I did try 0.03 and I still don't see the tray icon...

**Comment by puneetsl** [comment]
Can add more detail like which distro and WM you are using. Some window managers like Pantheon only allow whitelisted apps to add a tray icon.

**Comment by gammons** [comment]
I'm using an up-to-date arch distro, with i3 + polybar.  Polybar is the thing that controls the system tray.

**Comment by puneetsl** [comment]
Not sure how to fix in this particular combination. You would have to do some digging. I'll see if I can try this out on my end.

Maybe this can fix: https://github.com/polybar/polybar/issues/1355

**Comment by ArturoRis** [comment]
Hello,
I have the same problem: I can't see the tray icon.
I don't know if I can, somehow, check if it's just invisible or it's not created at all.

I'm using Linux Mint 19.2 with Cinnamon 4.2.4

**Comment by gammons** [comment]
side note @puneetsl I'd love to contribute to lotion, but it's not 100% clear how I can do that.  The actual app is tarred up in this repo, and the repo only contains a handful of supporting things like icons + an install script.

I'm wondering if it makes sense to un-tar the actual app, and have an actual make process that handles installation.  It'd encourage more contributions!

**Comment by puneetsl** [comment]
Sure, I think that's a good idea. I'll do that in the next release, which should happen soon.

**Comment by puneetsl** [comment]
With respect to tray icon not being part of the WM, Think some tinkering is needed from your end as well, to let me know what might be the reason. It is very difficult to support all the distros and WMs with all the intended features, and for this reason Nation is not releasing their native app for Linux.
