### ISSUE TITLE
Not working on Raspberry Pi

### ISSUE THREAD

**Issue by alminisl** [puneetsl/lotion#35]
Running latest raspbian and when doing the install script app is installed correctly however when launching it nothing happens.

Is there a way to debug this ?

**Comment by puneetsl** [comment]
Raspberry Pi uses ARM architecture, which is not yet supported. 

I'll see if we can do something about that. Thanks for reporting!

**Comment by alminisl** [comment]
Thanks! 

I've tried using electron packager and making build an ARM version, it did not work :( 

However I do not have much experience with Electron.

**Comment by puneetsl** [comment]
Fow now you can use chromium and create a shortcut. This is way less than ideal, but right now that might be the only option.
