### ISSUE TITLE
Most emoji unsupported

### ISSUE THREAD

**Issue by fruitfont** [puneetsl/lotion#37]
In Firefox, notion.so shows all emoji filled in and with color. On lotion, most emoji are rectangles, and the few that aren't are not in color.

**Comment by puneetsl** [comment]
Can you please let me know which distro and windows manager you are using?

**Comment by DrSh4dow** [comment]
> In Firefox, notion.so shows all emoji filled in and with color. On lotion, most emoji are rectangles, and the few that aren't are not in color.

Usually, that is dependant of system installed fonts, If you are on an Arch-based system, usually that problem resolves when you install the noto-fonts-emoji and the ttf-joypixels packages.
```
sudo pacman -S noto-fonts-emoji ttf-joypixels
```
I don't know what is the Debian or RedHat counterpart, but I guess if you install the respective emoji fonts the problem will resolve for you.
Cheers

**Comment by haydn-jones** [comment]
This is tangentially related, but when I install Lotion the full emoji set is _initially_ supported and after a few days it seems to break. Not really sure what is going on there. At first everything is fine, all emoji's look like what I see in Firefox on Notion.so, and then most turn black and white (maybe it starts using a totally different emoji font that isn't colored?).

This happened on Ubuntu 19.04, 19.10, and 20.04.

**Comment by DrSh4dow** [comment]
> This is tangentially related, but when I install Lotion the full emoji set is _initially_ supported and after a few days it seems to break. Not really sure what is going on there. At first everything is fine, all emoji's look like what I see in Firefox on Notion.so, and then most turn black and white (maybe it starts using a totally different emoji font that isn't colored?).
> 
> This happened on Ubuntu 19.04, 19.10, and 20.04.
@haydn-jones maybe you have more than one emoji font installed on your system, I don't know how to select one in specific, but in ubuntu Notion/Lotion works fine with the fonts-emojione package

```
sudo apt install fonts-emojione
```

**Comment by puneetsl** [comment]
Thanks @DrSh4dow for helping us out here :smile:

**Comment by DrSh4dow** [comment]
my pleasure @puneetsl 
it's the less I can do, thank you for the amazing Notion implementation 😁
