### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SzymonAntas** [puneetsl/lotion#4]
Hi Puneet,
![Screenshot from 2019-04-30 13-27-36](https://user-images.githubusercontent.com/29056888/56959286-3194cd00-6b4d-11e9-9c59-7d84caea6571.png)
I'm not sure whether this is related to the Lotion app or it is on Notion.so side.
Regardless of how many items I created I go over the Block limit - see the red bar msg on the top.
I'm sending this question also to Notion.so guys.

Thanks. BR
Szymon

**Comment by puneetsl** [comment]
Try to open Notion.so on your browser (preferably chromium based) and see if it still gives you this error. If there is also an error in the browser, I would suggest to report it on Notion's twitter account.  If not, then we will take a look into it. 

Thanks
