### ISSUE TITLE
Validation Error when trying to fetch resources

### ISSUE THREAD

**Issue by jcsawyer123** [puneetsl/lotion#42]
Once signed in, trying to access resources that are attached to a page provides an error response instead of the file.

Only seems to happen on this client, cannot replicate on the official windows version or the online version.

**Comment by puneetsl** [comment]
Can you share the screenshot of the error with a little more detail?

**Comment by jcsawyer123** [comment]
Returns JSON response in the below format, gets loaded into whatever text editor is my system default.

```json
{
"errorId":"95e0ad36-90c8-4818-b6c5-fc6b79965afe",
"name":"ValidationError",
"message":"User does not have access."
}
```

**Comment by puneetsl** [comment]
I could replicate, but this `JSON` opens up in my browser. 
To solve this you need to login to Notion from your browser as well. 

Let me know if this solves for you.

**Comment by jcsawyer123** [comment]
Apologies for the slow reply.

I have logged into my browser and it still does the same thing, it is a curious issue as this did not used to happen. Last time I used it was about 3 months ago.

**Comment by puneetsl** [comment]
Hmm that's weird. I'll try to replicate this issue

**Comment by puneetsl** [comment]
Should be fixed in news versions
