### ISSUE TITLE
Issue installing in Kubuntu 20.04

### ISSUE THREAD

**Issue by pablocal** [puneetsl/lotion#43]
I have used Lotion before and everything was ok. Recently I have updated my system to Kubuntu 20.04. I have tried to install (sudo) the app but I get this error:

```
cp: cannot create regular file '/root/.local/share/applications': No such file or directory
```
Thanks in advance.

**Comment by puneetsl** [comment]
Please don't use `sudo` while installing Lotion.

Lotion is designed to be used for user without root permissions.
