### ISSUE TITLE
Disable system tray icon

### ISSUE THREAD

**Issue by reid-harrison** [puneetsl/lotion#44]
Is there a way to disable the system tray icon? If not, I'd like to request that option! Thank you :)

![lotion_systemtray](https://user-images.githubusercontent.com/825437/81192464-4427ba80-8f88-11ea-87bd-e4be8c605e3e.png)

**Comment by puneetsl** [comment]
Is there a reason you would want to disable the system tray?

**Comment by reid-harrison** [comment]
Thanks for the follow-up, @puneetsl. Honestly I would mostly prefer the option to have a flat/monochrome icon to match others. I personally don't use tray icons and prefer using the dock to manage running applications but I understand that Lotion will continue running in the background even if the app window is closed. I'd actually like the option to disable this background running but that's a different issue.

How the Lotion icon looks alongside Steam, etc:
![lotion_icon_example](https://user-images.githubusercontent.com/825437/82740321-c3054d00-9d15-11ea-8ef2-2798afdac305.png)

**Comment by bnrobinson93** [comment]
Same. I like having the tray icon to show that it's running in the background and for quick access. I'd prefer a mono-chrome option. Also, I've noticed that if the tray icon is open and I open from the dock, a second tray icon will appear and a second app instance is opened.

**Comment by JCDetwiler** [comment]
I think relatedly, I found this while wondering why Lotion was still running several processing after quitting the GUI. Then I realized that the system tray icon isn't showing in i3 for me. So I currently have no way of exiting Lotion after killing the window but to send a signal to whichever I think the parent process is.

**Comment by puneetsl** [comment]
It's very difficult to add support for different WMs, one way to solve this is if you can create a flat version of the icon and add it the respective theme folder you are using. I have tested this in GNOME, not sure how to make it work in i3
