### ISSUE TITLE
Some keyboard shortcuts not working

### ISSUE THREAD

**Issue by yujia21** [puneetsl/lotion#46]
Hi,

Wondering if all desktop app keyboard shortcuts are supported? 

The following don't seem to work for me on Ubuntu 18.04:
- Ctrl + N for new page
- Ctrl + Shift + N for new window
- Ctrl + [, Ctrl + ] to go back and forward a page

Whereas the following do:
- Ctrl + Shift + L for dark mode
- Ctrl + P to open search

Thanks for the great work!

**Comment by puneetsl** [comment]
Noted!

Back and Forward works for me. I will try to add more shortcuts in the next release.

**Comment by puneetsl** [comment]
most shortcuts work now in version 0.05
