### ISSUE TITLE
Lotion may be able to work on Ubuntu 20.04

### ISSUE THREAD

**Issue by jahad9819jjj** [puneetsl/lotion#47]
Hello. I use this repo all the time. Thank you very much!

Now, I cloned and installed this repo on Ubuntu 20.04, but it was garbled as shown below. Do you have a solution for this?

I have already installed the packages:`fonts-emojione  fonts-noto-color-emoji`

![Screenshot from 2020-05-15 00-46-34](https://user-images.githubusercontent.com/40851882/81956169-f412bd00-9645-11ea-84ba-c5e9bd781cf0.png)

**Comment by puneetsl** [comment]
Hi! Ubuntu doesn't have native emoji support. You need to find the right config for you. Try solution provided in issue #37.
