### ISSUE TITLE
Most emojis aren't displayed

### ISSUE THREAD

**Issue by JorgeDLG** [puneetsl/lotion#48]
As you can see here:
![noIconsLotion](https://user-images.githubusercontent.com/44321931/82385138-ab864580-9a31-11ea-811d-65ca5416d066.gif)
System: 5.6.13-arch1-1
Notion: 2.7.22.4.3

**Comment by puneetsl** [comment]
Hi, 
Thanks for reporting. You need to install systemwide color emoji on Arch to fix this.
This blog might help: https://chrpaul.de/2019/07/Enable-colour-emoji-support-on-Manjaro-Linux.html

Let me know if it worked for you!

Thanks

**Comment by JorgeDLG** [comment]
> Hi,
> Thanks for reporting. You need to install systemwide color emoji on Arch to fix this.
> This blog might help: https://chrpaul.de/2019/07/Enable-colour-emoji-support-on-Manjaro-Linux.html
> 
> Let me know if it worked for you!
> 
> Thanks

Thanks for the info!
