### ISSUE TITLE
Disable Smooth Scrolling

### ISSUE THREAD

**Issue by piktonus97m** [puneetsl/lotion#49]
Hello team, 
Is there a way to disable Smooth Scrolling? 
Thanks in advance. 

Thanks for making this project live, btw.

**Comment by puneetsl** [comment]
Hi!

Thanks for creating an issue! 
By saying smooth scrolling, do you mean that the page continues scrolling even though the user has stepped away from the interaction?
Can you let me know what distro and WM you are using?

Thanks

**Comment by piktonus97m** [comment]
`printf 'Desktop: %s\nSession: %s\n' "$XDG_CURRENT_DESKTOP" "$GDMSESSION"
Desktop: pop:GNOME
Session: pop
`

**Comment by falqas** [comment]
I think @piktonus97m is referring to the Electron/Chromium runtime feature (you can also find it in under Chrome's flags: chrome://flags:/#smooth-scrolling)
On some Linux builds it can be very laggy/distracting, and is especially noticeable when using a mouse scroll wheel (I've noticed it on Ubuntu 16.04 & 18.04, using a Logitech MX Ergo)
Luckily you can disable it in most Electron apps by appending the `disable-smooth-scrolling` flag to the executable, ie: 
`lotion --disable-smooth-scrolling`

+1 thanks to @puneetsl for this cool project!
