### ISSUE TITLE
Gnome 3: compatibility

### ISSUE THREAD

**Issue by puneetsl** [puneetsl/lotion#5]
Add icon compatibility for Gnome 3. Right now the app is opened using a separate icon.
![Img](https://user-images.githubusercontent.com/29056888/56959286-3194cd00-6b4d-11e9-9c59-7d84caea6571.png)

**Comment by puneetsl** [comment]
Fixed!
I will close this once any other user confirms that it is fixed

**Comment by HymanZHAN** [comment]
Using DashToDock on Fedora30 and I don't have this issue.

**Comment by puneetsl** [comment]
Thanks for confirming! Closing this issue.
