### ISSUE TITLE
Not opening on zorin OS

### ISSUE THREAD

**Issue by Kurt1968** [puneetsl/lotion#50]
Hi, I succesfully installed the app using install.sh script, but when I try opening it nothing happens.
I'm running on zorin OS ubuntu based 32-bit

**Comment by puneetsl** [comment]
Unfortunately, Electron does not support 32 bit OS. 
https://www.electronjs.org/blog/linux-32bit-support 

The best way for you is to use Chrome and create a shortcut, which kind of looks like an app.
