### ISSUE TITLE
Uncaught exception: Object has been destroyed

### ISSUE THREAD

**Issue by Matoo125** [puneetsl/lotion#53]
Hello, I'm getting often this exception
![exception](https://user-images.githubusercontent.com/10489019/82800836-a0da0f00-9e7c-11ea-8c71-3339b93ee44b.png)
It's kind of annoying to use since it pops out regularly. Any idea how to fix it? 
Thanks a lot.

**Comment by Matoo125** [comment]
Ok, so it wasn't able to save the content but restart helped and saved the local data without any loss.

**Comment by puneetsl** [comment]
Thanks for reporting!
Can you specify distro and window manager you are using with steps to replicate this issue?

**Comment by Matoo125** [comment]
Thanks for your response.
No idea how it happened, but I use default ubuntu 19.10 with GNOME.
And problem doesn't seem to continue after restart.

**Comment by puneetsl** [comment]
Alright that might be some random `electron` bug. I think for now I'll close this issue. Reopen if that happens again!
