### ISSUE TITLE
Opening a second window?

### ISSUE THREAD

**Issue by mtoohey31** [puneetsl/lotion#54]
Hello! I'm wondering what the keyboard shortcut is to open a new window or if this functionality exists. On MacOS and Windows I can use Ctrl/Command + Shift + N to open a new window, but that isn't doing anything in Linux.

**Comment by navhaxs** [comment]
Looks like nativefier doesn't support this... yet.

https://github.com/jiahaog/nativefier/issues/983

Multiple windows is most definitely a compelling case for the Notion app - editing multiple pages/copy paste etc. rather than going needing to go back and forth.

**Comment by joshpetit** [comment]
If you install the native notion (instructions outlined in #1, but I also created a script on my [fork](https://github.com/joshpetit/lotion) to automate installation) it will allow you to use ctrl + shift + n to create new windows, also makes the app available offline which is cool too.

**Comment by guillaumefrd** [comment]
Thanks @joshpetit multiple windows works great with Native Notion indeed. And your script works perfectly!
