### ISSUE TITLE
feature request: Automatic dark mode toggling based on OS theme

### ISSUE THREAD

**Issue by mschmidm** [puneetsl/lotion#55]
First of all, thank you for the great app!
It would be really cool if the lotion darkmode would be automatically activated based on the OS theme. My OS switches automatically to dark mode on evening and it would be a pleasure to have the lotion darkmode toggled automatically!
Thank you in advance! :)

**Comment by puneetsl** [comment]
Its a bit hard to implement based on various Linux window managers, you can use `CTRL+SHIFT+L` to toggle the theme quickly
