### ISSUE TITLE
Change the default icon

### ISSUE THREAD

**Issue by d-folt** [puneetsl/lotion#57]
I'm having trouble with the default blue icon as it's not going with my current theme.Is there a way I can change that?

**Comment by puneetsl** [comment]
Yes, it is as simple as going to the folder where you installed lotion and replacing `icon.png`.

Let me know if it doesn't work for you

**Comment by d-folt** [comment]
it worked.thanks

**Comment by BrunoRasera** [comment]
I changed mu icon.png but it's still using the purple one...
