### ISSUE TITLE
[issue] links opens in browser, sometimes

### ISSUE THREAD

**Issue by luismanson** [puneetsl/lotion#59]
Hello, when I search for something in "quick find" and click a result it opens in my browser, when I come back to lotion, and repeat all, this time will open in Lotion normally. Also, the issue while sporadic its annoying. How can I help to investigate this when it repeats

**Comment by nindroz** [comment]
does anyone plan to take this as this has escalated for me to anything I click on the sidebar opens as a link

**Comment by angryweasel** [comment]
FWIW - I see this on the first click of a sidebar link after launching Notion every time - but also after Lotion has been idle for some time (it cold be that it's restarted for some reason during this idle period).

**Comment by angryweasel** [comment]
but to be fair, this part of the code is (should be) identical between platforms, but worth pointing out that I cannot reproduce this  behavior on my mac app.

**Comment by puneetsl** [comment]
These issues should be fixed in news version 0.05, if not please open a new issue
