### ISSUE TITLE
Missing icons on GNOME 3

### ISSUE THREAD

**Issue by ar-tour** [puneetsl/lotion#6]
![Screenshot from 2019-07-31 20-44-45](https://user-images.githubusercontent.com/43483716/62238937-784fc880-b3c3-11e9-9ec1-3a8a46dd1557.png)

**Comment by puneetsl** [comment]
Well, it depends on which distro you are using. If you are using anything Ubuntu related you can use this guide to install emojis:
https://discourse.ubuntu.com/t/try-color-emoji-in-18-04/1492

**Comment by ar-tour** [comment]
Yes, it's Ubuntu 19.04. Thanks for answer :)

**Comment by puneetsl** [comment]
Let me know if it worked for you. I have also provided some opensource icons/emojis https://github.com/puneetsl/lotion/tree/master/pngicons which you can use for your use case.

**Comment by puneetsl** [comment]
Closing this

**Comment by MoltenMuffins** [comment]
How would I go about using the icons/emojis provided by you in the repo for lotion?
