### ISSUE TITLE
Release file in repository

### ISSUE THREAD

**Issue by Fogapod** [puneetsl/lotion#60]
Hello, what is https://github.com/puneetsl/lotion/blob/master/Lotion-linux-x64.tar.xz doing in repository?
Releases should be uploaded into releases section: https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release
Uploading releases directly into repository will increase repository size quickly.

**Comment by puneetsl** [comment]
Should be fixed in #107
