### ISSUE TITLE
ALT-key menu bar

### ISSUE THREAD

**Issue by toolittlecakes** [puneetsl/lotion#61]
Great application, but I have a problem: I need to switch languages ​​quite often. I'm used to the Alt + Shift keyboard shortcut. But in the lotion, when I do this, a menu bar appears at the top of the application. This is really annoying. Is there any way to change this behavior?

**Comment by joshpetit** [comment]
This is likely because you're just using the web wrapper version, have you tried using the [native](#1) one?

**Comment by puneetsl** [comment]
Should be fixed in version 0.05! open a new issue if it persists
