### ISSUE TITLE
UI Font

### ISSUE THREAD

**Issue by AbhigyanKumar** [puneetsl/lotion#65]
I want to have the _Arial_, _Helevetica Neue_ or _SF Pro Display_ font instead of _Noto Sans_ in Lotion.

**Comment by liuseemin** [comment]
I want this feature too, but I guess this can't be done because lotion is just a web app wrapper for notion, and change font cannot be achieved even on it's native website.

**Comment by AbhigyanKumar** [comment]
Hey @liuseemin, seems you're **right**. I must close this repo soon.
