### ISSUE TITLE
Enable zoom in/out functionality

### ISSUE THREAD

**Issue by josephpconley** [puneetsl/lotion#67]
https://www.geeksforgeeks.org/zoom-functionality-in-electronjs/

Certainly a nice-to-have, to allow zoom in/out capabilities for the app.  Thanks!

**Comment by puneetsl** [comment]
Does `CTRL` + `+` work for zooming in for you?

I generally use this to zoom in

**Comment by josephpconley** [comment]
It does not, I'm currently on Ubuntu 18.04.5 LTS

**Comment by puneetsl** [comment]
when you press Alt/option key and the menu appears, if you click on `View` you can see your shortcut for zooming in
![image](https://user-images.githubusercontent.com/6509604/90087024-c6432000-dce9-11ea-9b7e-04a09d2c94ee.png)

**Comment by josephpconley** [comment]
Got it, thank you!!!

**Comment by puneetsl** [comment]
Resolved
