### ISSUE TITLE
Non-native stuck on external url

### ISSUE THREAD

**Issue by jeffmcneill** [puneetsl/lotion#71]
I embedded a widget that then changed to an external URL and no way to go "back". Every time the Lotion app (non-native) is opened it is on that page. I also installed the native version and am able to create a New Window, and then close the old window (which is also trapped on the external site).

**Comment by puneetsl** [comment]
to go back/forward you can use `CTRL+[` and `CTRL+]`, also you can press alt to see menu in web version where if you go to `view` submenu you can go back and forward by clicking.

**Comment by jeffmcneill** [comment]
I cannot go back to the web version. It just loads the home page of Notion, and when I click Login it opens a tab in my browser. There is no going back, and refresh doesn't work, it just stays on the home page (in the web version of the app).
