### ISSUE TITLE
Can I switch it back to the default Notion font?

### ISSUE THREAD

**Issue by samm-sepi0l** [puneetsl/lotion#72]
Excellent port, only thing I dislike is the font, is there any way I could switch it back to the old Segoe-UI of the default Notion? (or whatever the original font is)

**Comment by puneetsl** [comment]
We did not change the fonts, you can select the fonts from one these in the preferences
![image](https://user-images.githubusercontent.com/6509604/115104258-319e5b00-9f25-11eb-8c58-448ee23a708f.png)
