### ISSUE TITLE
Visual bug when opening page as modal

### ISSUE THREAD

**Issue by iago-mendes** [puneetsl/lotion#77]
When you open a page as a modal (not full screen), the background page has a visual bug.
Here is an example:

![Background page](https://i.ibb.co/4KqWzsy/Screenshot-from-2020-10-06-22-11-08.png "Background page")
![Modal page](https://i.ibb.co/DRjQwHp/Screenshot-from-2020-10-06-22-11-23.png "Modal page")

**Comment by puneetsl** [comment]
Should be fixed in the new version 0.05
