### ISSUE TITLE
How to change icon back to native notion icon?

### ISSUE THREAD

**Issue by ChiHangChen** [puneetsl/lotion#86]
I already download native notion icon and move the icon to 
`~/.local/share/lotion/icon.png` and `~/.local/share/lotion/Lotion/resources/app/icon.png`

But when I open lotion, it still be blue icon displayed and my native icon next to it without any function.

![image](https://user-images.githubusercontent.com/22412708/102735430-5f3e1380-433a-11eb-8065-2ad1e61454eb.png)

Oh, I just fixed it by kill all lotion jobs and run again, but the moment I start lotion it will still be a transparent icon besides it and disappear after few seconds.

Also, I wonder why sometimes I click my page in lotion it will open with browser rather then in lotion?

**Comment by joshpetit** [comment]
Can you look inside `~/.local/share/applications/Lotion.desktop`
and verify that the `Icon` field is set like this `Icon=/home/user/path/to/icon.png`?
