### ISSUE TITLE
"[sudo] ./setup.sh install" returns command not found error

### ISSUE THREAD

**Issue by quietmansoath** [puneetsl/lotion#88]
I navigated to where the .sh file downloaded to (/home). I ran [sudo] ./setup.sh install with and without sudo, but keep getting that the command isn't found. Not sure what I'm doing wrong. Can someone help?

**Comment by aouini-oussama** [comment]
same issue :( 
![image](https://user-images.githubusercontent.com/59149244/103582870-f9778d00-4ede-11eb-9d93-2a68c45c9641.png)

**Comment by Mazurel** [comment]
It is probably because `setup.sh` is not executable, to fix you should run `chmod +x setup.sh` beforehand.

**Comment by aouini-oussama** [comment]
> It is probably because `setup.sh` is not executable, to fix you should run `chmod +x setup.sh` beforehand.

yess u got it right thnx a lot men @ <3

**Comment by puneetsl** [comment]
Also, I'd refrain from using `sudo` with anything you download from the internet. Although I am the maintainer of this repo but still I'd rather install this locally.
