### ISSUE TITLE
No Spellcheck?

### ISSUE THREAD

**Issue by cstby** [puneetsl/lotion#91]
I ran the native install script on Pop!_OS 20.04, and spell check functionality is completely missing. Is this expected?

**Comment by joshpetit** [comment]
I'm fairly certain this has to do with the version of notion that's currently being cloned (2.0.9). I'm working on updating it and finding a way to enable the auto-updater so that it'll be a practically native experience.

**Comment by thanhtacles** [comment]
At best I would love the ability to disable spellcheck. There's no option to get rid of that redsquiggle or add to dictionary.

**Comment by puneetsl** [comment]
This should be somewhat fixed in version 0.05 of lotion
