### ISSUE TITLE
Lotion icon not showing in launch bar and alt+tab

### ISSUE THREAD

**Issue by mbbroberg** [puneetsl/lotion#94]
Hey gang, thank you so much for making Lotion a handy native app for Linux users :smile:. I have a question I've been troubleshooting for some time and running against the edge of my knowledge here. Both the launch bar and Alt+Tab switcher show a blank icon whenever I switch to Lotion. Ex: 

![Screenshot from 2021-01-22 08-16-12](https://user-images.githubusercontent.com/1744971/105508373-e95afe00-5c91-11eb-8368-23055014c988.png)

I've run the installer a few times as I updated the versions from source. I see everything looking normal in `/home/mbbroberg/.local/share/lotion` and the .desktop item looks okay too: 

```bash
.local/share/lotion 
❯ ls
48x48/     Fonts/    LICENSE  Lotion.desktop*  pngicons/  setup.sh*
clean.sh*  icon.png  Lotion/  Notion.png       README.md  uninstall.sh*

.local/share/lotion 
❯ cat ../applications/Lotion.desktop 
[Desktop Entry]
Name=Notion
Name[en_US]=Lotion
Comment=Unofficial Notion.so application for Linux
Exec="/home/mbbroberg/.local/share/lotion/Lotion/Lotion"
Terminal=false
Categories=Office;TextEditor;Utility
Type=Application
Icon=/home/mbbroberg/.local/share/lotion/icon.png
StartupWMClass=
```

You'll see I messed around with making a 48x48 folder in `share/lotion/` while following [this specification on Gnome](https://developer.gnome.org/icon-theme-spec/), but it did not have an effect one way or another. 

I'm on Fedora running Gnome 3.38.0. Any tips to get this icon to load? 

Thanks!

**Comment by joshpetit** [comment]
I just took a look into it, Just to verify iss your Lotion.desktop file within ~/.local/share/applications/Lotion.desktop? Thanks a lot!

**Comment by mbbroberg** [comment]
Thanks @joshpetit! Yes, that correct, it's under  ~/.local/share/applications/Lotion.desktop.

**Comment by joshpetit** [comment]
@mbbroberg I see that your `StartupWMClass` is not set equal to Notion. I doubt that's the problem, but try putting `StartupWMClass=Notion`. After that could you verify that the icon.png is an actual image. Thanks for linking to the GNOME specification, I'll make sure to create an issue so that it's done correctly.

**Comment by mbbroberg** [comment]
@joshpetit oh wow, that did it!! I restarted and immediately had the iconography! I'm offering up a PR to match my solution. 

![Screenshot from 2021-01-25 08-02-46](https://user-images.githubusercontent.com/1744971/105715891-c162d900-5ee3-11eb-9347-764d94cbc029.png)

This aligns with the specification details I read about StartupWMClass as well. If there's a reason to keep the variable that I'm missing feel free to close this and the PR. Thanks either way @joshpetit :clap:
