### ISSUE TITLE
Color Emojis not displayed inside of text

### ISSUE THREAD

**Issue by jeffmcneill** [puneetsl/lotion#95]
Hello, this issue is not about the emojis used as the page favicon, but the use of emojis inside of Notion inline with text. An example is how the color emojis (white, red, green, blue) appear when in a formula. The colored one is the Notion distribution based on Windows Notion app, and the grey ones are Lotion. 

I'm using Debian Testing and have installed the color emoji fonts, and they work in general and for the other app but not Lotion. I prefer Lotion because it has a proper icon in the taskbar, and it seems to take up less memory.

![Screenshot from 2021-01-23 17-01-35](https://user-images.githubusercontent.com/3119827/105575326-658e3800-5d9d-11eb-8f24-25b5ab0e5a0b.png)
![Screenshot from 2021-01-23 17-01-03](https://user-images.githubusercontent.com/3119827/105575329-66bf6500-5d9d-11eb-8631-a1d148cb66ab.png)

**Comment by jeffmcneill** [comment]
Similar to #8

**Comment by joshpetit** [comment]
Thanks for the report! I tried replicating this, but it seems the only emoji I have difficulty viewing is the "Medium White Circle"
![image](https://user-images.githubusercontent.com/59021155/105628328-3bbf2a80-5e0a-11eb-8184-c2394c1bf75e.png).
Are you using the native or web version?

**Comment by jeffmcneill** [comment]
Hi, the 0.04 Lotion is the only Notion that does not show me color emojis. If I change the font family using the inspect tool then it works so it is obviously Segoe UI that is the issue. My guess is that Lotion is not looking at local font config, and other apps are, but only a guess. The other dist of Notion that is the Windows app does not have this issue, not does the web using chromium

**Comment by joshpetit** [comment]
I see your problem. Try recloning the repo and installing the native and then the web version to see if there is any difference. I think @puneetsl might know a bit more about why your install seems to have this issue.

**Comment by jeffmcneill** [comment]
Did the reinstall, chose the web app (it said native was not available), still same issue with the colored buttons, however some icons are showing up in color, so it may just be those specific icons. Will test and report back.

**Comment by joshpetit** [comment]
It said native not available? Could you post the error message please. I'm in the process of trying to get the native client updated to 2.0.11 (it's currently 2.0.9). And I would think that would solve some problems but considering that the web app is the latest version and you still seem to have problems I'll mess around with nativefier and see what options can be changed to fix it completely.

**Comment by jeffmcneill** [comment]
I got native to work. It is fine. The web version has the same problem as before. Did a fresh install of both to test.

**Comment by puneetsl** [comment]
Can you try the newer version, hopefully it fixes this issue

**Comment by jeffmcneill** [comment]
Hi, sorry for the delay on this. V. 0.05 of the web version works fine now. Thanks!
