### ISSUE TITLE
Add shortcut or button to clear app cache

### ISSUE THREAD

**Issue by mbbroberg** [puneetsl/lotion#97]
I have had a few days of slow search speeds and recently [tweeted at Notion](https://twitter.com/NotionHQ/status/1356815432330604544?s=20) about it. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Uh oh, sorry for the trouble and the delayed reply! Our servers were up and running at this time - are you still experiencing issues?<br><br>If so, does resetting your app cache help?<a href="https://t.co/WZWdOQ4ajy">https://t.co/WZWdOQ4ajy</a></p>&mdash; Notion (@NotionHQ) <a href="https://twitter.com/NotionHQ/status/1356815432330604544?ref_src=twsrc%5Etfw">February 3, 2021</a></blockquote>

The resetting of app cache did the trick! However, to get there in Lotion, I launched Developer Tools then went Application > Clear Storage > Clear site data. 

I'm wondering if there's a good place to add this troubleshooting feature. As a user, the View tab seems to have the other key options like this, so adding it there might make sense. Something like Ctrl+Shift+C for cache could do it. 

Thanks all!

**Comment by joshpetit** [comment]
Ok, I see, how often do you have to clear your cache? If it is only a one-time thing I'm not sure if it merits a feature. If it happens multiple times though then I think it would make sense. The basic app is created with [nativefier](https://github.com/nativefier/nativefier) and then scripts are added to install + configure it properly. We can bind keys to run javascript to clear the cache.

Thanks, let me know if this isn't just a one-time thing!

**Comment by mbbroberg** [comment]
@joshpetit totally! I'm not sure if it will be a more-than-one-time thing at the moment. I'm comfortable closing it for now and reopening if it comes up for me or other users. I just wanted to get the workaround out there as well. Hope it helps -- closing for now.
