### ISSUE TITLE
(solved) 7z is required

### ISSUE THREAD

**Issue by tkakcy159** [puneetsl/lotion#99]
I clone this repo and excute 'sudo ./setup.sh web' command.
I'm already installed p7zip

ubuntu@synology_lxqt:~/Desktop/program/notion/lotion$ sudo ./setup.sh web
Command 7z is required to run this script

**This case, you have to install 'p7zip-ful' package NOT 'p7zip'**

**Comment by dongzx666** [comment]
> I clone this repo and excute 'sudo ./setup.sh web' command.
> I'm already installed p7zip
> 
> ubuntu@synology_lxqt:~/Desktop/program/notion/lotion$ sudo ./setup.sh web
> Command 7z is required to run this script
> 
> **This case, you have to install 'p7zip-ful' package NOT 'p7zip'**

maybe it's '**p7zip-full**' not 'p7zip-ful'

**Comment by gitSaptarshi** [comment]
Hi, in Solus the package is named `p7zip` only.

**Comment by joshpetit** [comment]
@tkakcy159 is seems like you've had this solved? Glad you could get it working! I'll close this for now.
